version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: always
    volumes:
      - nginx-proxy:/etc/nginx/conf.d/
    ports:
      - "80:80"

  dockergen:
    image: jwilder/docker-gen:0.7.3
    depends_on:
      - nginx
    command: -notify-sighup reverse-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy:/etc/nginx/conf.d/
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

volumes:
  nginx-proxy:

networks:
  default:
    external:
      name: reverse-proxy
